version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Instalamos dependencias en el docker..."
      - echo "Actualizamos la funcion lambda..."
      - aws lambda update-function-code --function-name update-function-code --s3-bucket fromsnowtos3 --s3-key connector/deployment_package.zip
      - echo "Hecho!!!"